// src/services/aiService.ts

export const aiProcessor = {
  async processVoiceCommand(command: string, language: string) {
    console.log(`Processing: ${command}`);
    return {
      success: true,
      formattedText: "This is a sample document content generated by AI based on your command.",
      intent: 'letterhead'
    };
  }
};
