const fs = require('fs');
const path = require('path');

const filePath = path.resolve(__dirname, '../src/components/auth-ui.tsx');
let content = fs.readFileSync(filePath, 'utf8');

// Find the index of 'type SocialAuthButtonProps = {'
const splitKey = 'type SocialAuthButtonProps = {';
const splitIdx = content.indexOf(splitKey);
if (splitIdx === -1) {
  console.error('Could not find split key');
  process.exit(1);
}

const before = content.substring(0, splitIdx).trim();

const tail = [
  'type SocialAuthButtonProps = {',
  '  provider: "apple" | "google";',
  '  onPress: () => void;',
  '  loading?: boolean;',
  '  disabled?: boolean;',
  '  unavailable?: boolean;',
  '};',
  '',
  'type AuthCheckboxProps = {',
  '  checked: boolean;',
  '  onPress: () => void;',
  '  children: ReactNode;',
  '};',
  '',
  'export function AuthLayout({ children }: AuthLayoutProps) {',
  '  const { isDark, theme } = useAppTheme();',
  '',
  '  return (',
  '    <ScrollView',
  '      style={[styles.page, { backgroundColor: theme.background }]}',
  '      contentContainerStyle={{',
  '        flexGrow: 1,',
  '        alignItems: "center",',
  '        justifyContent: "center",',
  '        padding: 20,',
  '      }}',
  '      keyboardShouldPersistTaps="handled"',
  '    >',
  '      <Animated.View',
  '        entering={FadeIn.duration(350)}',
  '        style={[',
  '          styles.authCardContainer,',
  '          {',
  '            backgroundColor: theme.card,',
  '            borderColor: isDark ? "rgba(255,255,255,0.08)" : "#E2E8F0",',
  '          },',
  '        ]}',
  '      >',
  '        {children}',
  '      </Animated.View>',
  '    </ScrollView>',
  '  );',
  '}',
  '',
  'export function AuthInput({',
  '  placeholder,',
  '  value,',
  '  onChangeText,',
  '  autoComplete,',
  '  autoCapitalize = "sentences",',
  '  keyboardType,',
  '  secureTextEntry,',
  '  leftIcon,',
  '  rightAction,',
  '}: AuthInputProps) {',
  '  const [focused, setFocused] = useState(false);',
  '  const { theme } = useAppTheme();',
  '',
  '  return (',
  '    <View style={[',
  '      styles.inputFrame,',
  '      { backgroundColor: theme.inputSurface, borderColor: theme.line },',
  '      focused && { borderColor: BrandColors.primary, backgroundColor: theme.card },',
  '    ]}>',
  '      {leftIcon ? <Ionicons name={leftIcon} size={19} color="#64748B" style={{ marginLeft: 14, marginRight: -4 }} /> : null}',
  '      <TextInput',
  '        accessibilityLabel={placeholder}',
  '        placeholder={placeholder}',
  '        placeholderTextColor={theme.muted}',
  '        style={[styles.input, { color: theme.ink }, rightAction ? styles.inputWithAction : undefined]}',
  '        keyboardType={keyboardType}',
  '        autoCapitalize={autoCapitalize}',
  '        autoComplete={autoComplete}',
  '        secureTextEntry={secureTextEntry}',
  '        value={value}',
  '        onChangeText={onChangeText}',
  '        onBlur={() => setFocused(false)}',
  '        onFocus={() => setFocused(true)}',
  '      />',
  '      {rightAction ? <View style={styles.inputAction}>{rightAction}</View> : null}',
  '    </View>',
  '  );',
  '}',
  '',
  'export function PasswordVisibilityButton({ visible, onPress }: { visible: boolean; onPress: () => void }) {',
  '  const { theme } = useAppTheme();',
  '  return (',
  '    <Pressable',
  '      onPress={onPress}',
  '      hitSlop={12}',
  '      accessibilityRole="button"',
  '      accessibilityLabel={visible ? "Hide password" : "Show password"}',
  '      style={({ pressed }) => [styles.passwordIconButton, pressed && styles.iconPressed]}',
  '    >',
  '      <Ionicons name={visible ? "eye-off-outline" : "eye-outline"} size={21} color={theme.muted} />',
  '    </Pressable>',
  '  );',
  '}',
  '',
  'export function AuthCheckbox({ checked, onPress, children }: AuthCheckboxProps) {',
  '  const { theme } = useAppTheme();',
  '  return (',
  '    <Pressable',
  '      accessibilityRole="checkbox"',
  '      accessibilityState={{ checked }}',
  '      onPress={onPress}',
  '      style={({ pressed }) => [styles.checkboxRow, pressed && styles.checkboxPressed]}',
  '    >',
  '      <View style={[styles.checkboxBox, { borderColor: theme.line }, checked && { backgroundColor: BrandColors.primary, borderColor: BrandColors.primary }]}>',
  '        {checked ? <Ionicons name="checkmark" size={15} color="#FFFFFF" /> : null}',
  '      </View>',
  '      <View style={styles.checkboxContent}>{children}</View>',
  '    </Pressable>',
  '  );',
  '}',
  '',
  'export function AuthPrimaryButton({ label, loading, disabled, showArrow, onPress }: AuthPrimaryButtonProps) {',
  '  return (',
  '    <Pressable',
  '      style={({ hovered, pressed }) => [',
  '        styles.primaryButton,',
  '        { backgroundColor: BrandColors.primary, borderRadius: 24, height: 50 },',
  '        hovered && !disabled && styles.primaryButtonHover,',
  '        pressed && !disabled && { opacity: 0.85 },',
  '        disabled && styles.primaryButtonDisabled,',
  '      ]}',
  '      onPress={onPress}',
  '      disabled={disabled}',
  '      accessibilityRole="button"',
  '      accessibilityLabel={label}',
  '    >',
  '      {loading ? (',
  '        <ActivityIndicator color="#FFFFFF" />',
  '      ) : (',
  '        <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }}>',
  '          <Text style={[styles.primaryButtonText, { fontSize: 16, fontWeight: "700" }]}>{label}</Text>',
  '          {showArrow ? <Ionicons name="arrow-forward" size={19} color="#FFFFFF" /> : null}',
  '        </View>',
  '      )}',
  '    </Pressable>',
  '  );',
  '}',
  '',
  'export function InfoBox({ text }: { text: string }) {',
  '  const { isDark, theme } = useAppTheme();',
  '  return (',
  '    <View style={[styles.infoBox, { backgroundColor: theme.accentSurface, borderColor: theme.accentBorder }]}>',
  '      <Ionicons name="information-circle" size={20} color={BrandColors.primary} style={{ marginTop: 1 }} />',
  '      <Text style={[styles.infoBoxText, { color: isDark ? "#FED7AA" : "#7C2D12" }]}>{text}</Text>',
  '    </View>',
  '  );',
  '}',
  '',
  'export function ConfettiSuccess({ title, subtitle }: { title: string; subtitle: string }) {',
  '  const { isDark } = useAppTheme();',
  '  return (',
  '    <View style={{ alignItems: "center", marginVertical: 24, gap: 14 }}>',
  '      <View style={{ width: 90, height: 90, borderRadius: 45, backgroundColor: isDark ? "rgba(22, 163, 74, 0.2)" : "#DCFCE7", alignItems: "center", justifyContent: "center" }}>',
  '        <View style={{ width: 66, height: 66, borderRadius: 33, backgroundColor: "#16A34A", alignItems: "center", justifyContent: "center" }}>',
  '          <Ionicons name="checkmark" size={40} color="#FFFFFF" />',
  '        </View>',
  '      </View>',
  '      <Text style={{ fontSize: 24, fontWeight: "800", color: isDark ? "#FFFFFF" : "#0F172A", textAlign: "center", marginTop: 8 }}>{title}</Text>',
  '      <Text style={{ fontSize: 14, fontWeight: "500", color: "#64748B", textAlign: "center", maxWidth: 320, lineHeight: 20 }}>{subtitle}</Text>',
  '    </View>',
  '  );',
  '}',
  '',
  'export function AuthDivider({ label = "OR" }: { label?: string }) {',
  '  const { theme } = useAppTheme();',
  '  return (',
  '    <View style={styles.dividerRow}>',
  '      <View style={[styles.dividerLine, { backgroundColor: theme.line }]} />',
  '      <Text style={[styles.dividerLabel, { color: theme.muted }]}>{label}</Text>',
  '      <View style={[styles.dividerLine, { backgroundColor: theme.line }]} />',
  '    </View>',
  '  );',
  '}',
  '',
  'export function SocialAuthButton({ provider, onPress, loading, disabled, unavailable }: SocialAuthButtonProps) {',
  '  const isApple = provider === "apple";',
  '  const { isDark, theme } = useAppTheme();',
  '',
  '  return (',
  '    <Pressable',
  '      style={({ hovered, pressed }) => [',
  '        styles.socialButton,',
  '        {',
  '          backgroundColor: isDark ? "#1C202A" : "#FFFFFF",',
  '          borderColor: isDark ? "#303646" : "#DFDED7",',
  '          borderWidth: 1,',
  '        },',
  '        hovered && !disabled && !loading && { backgroundColor: isDark ? "#242A36" : "#F7F6F2" },',
  '        pressed && !disabled && !loading && { opacity: 0.9 },',
  '        (disabled || loading || unavailable) && { opacity: 0.5 },',
  '      ]}',
  '      onPress={onPress}',
  '      disabled={disabled || loading}',
  '      accessibilityRole="button"',
  '      accessibilityLabel={isApple ? "Continue with Apple" : "Continue with Google"}',
  '      accessibilityState={{ disabled: !!disabled || !!loading || !!unavailable }}',
  '    >',
  '      {loading ? (',
  '        <ActivityIndicator color={theme.ink} />',
  '      ) : (',
  '        <View style={styles.socialButtonContent}>',
  '          <Image',
  '            source={isApple ? (isDark ? authLogos.appleWhite : authLogos.appleBlack) : authLogos.google}',
  '            style={{ width: 20, height: 20, marginRight: 8 }}',
  '            contentFit="contain"',
  '            transition={0}',
  '            accessibilityLabel={isApple ? "Apple logo" : "Google logo"}',
  '          />',
  '          <Text style={[styles.socialButtonText, { color: theme.ink }]}>',
  '            {isApple ? "Continue with Apple" : "Continue with Google"}',
  '          </Text>',
  '        </View>',
  '      )}',
  '    </Pressable>',
  '  );',
  '}',
].join('\n');

fs.writeFileSync(filePath, before + '\n\n' + tail + '\n');
console.log('Successfully formatted auth-ui.tsx!');
